name: video_extract
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
    - playwright
    - google-genai
    - openai # 新增
    - fastapi
    - uvicorn
    - python-dotenv
    - httpx
    - browser-cookie3
    - keyring
